sudo: false
env:
  global:
  - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
  - USE_CYTHON=false
  - USE_CYTHON=true
addons:
  apt:
    packages:
    - gfortran
language: python
matrix:
  include:
  - python: '2.7'
    env:
    - PYTHON_VERSION="2.7"
  - python: '3.4'
    env:
    - PYTHON_VERSION="3.4"
  - python: '3.5'
    env:
    - PYTHON_VERSION="3.5"
  - python: '3.6'
    env:
    - PYTHON_VERSION="3.6"
before_install:
- pip install pytest 
install: source continuous_integration/install.sh
#script: eval xvfb-run pytest .
script: python -m pytest  tests/
